import type { Person, Task } from './tasks';
import { startOfToday } from './tasks';

/*
  TEMP: the seed the screens read until GET /me/day and GET /board/:slug exist.
  Kept out of the store so swapping it for a fetch is a one-line change.

  Dates are generated relative to today so the overdue, due-today and next-week
  groupings on My Day stay meaningful whenever this is opened.
*/

function iso(offsetDays: number): string {
  const d = startOfToday();
  d.setDate(d.getDate() + offsetDays);
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
}

function ago(hours: number): string {
  return new Date(Date.now() - hours * 3_600_000).toISOString();
}

export const PEOPLE: Record<string, Person> = {
  riya: { id: 'p-riya', name: 'Riya S.', initials: 'RS', domain: 'core' },
  arjun: { id: 'p-arjun', name: 'Arjun M.', initials: 'AM', domain: 'events' },
  ananya: { id: 'p-ananya', name: 'Ananya R.', initials: 'AR', domain: 'design' },
  karan: { id: 'p-karan', name: 'Karan M.', initials: 'KM', domain: 'events' },
  nithya: { id: 'p-nithya', name: 'Nithya P.', initials: 'NP', domain: 'technical' },
  dev: { id: 'p-dev', name: 'Dev A.', initials: 'DA', domain: 'media' },
  sana: { id: 'p-sana', name: 'Sana K.', initials: 'SK', domain: 'management' },
};

/** The boards the nav can reach. Slug is the URL segment (§9.7). */
export const BOARDS = [
  { slug: 'design', name: 'Design', domain: 'design' as const, members: 9 },
  { slug: 'technical', name: 'Technical', domain: 'technical' as const, members: 12 },
  { slug: 'events', name: 'Events', domain: 'events' as const, members: 11 },
  { slug: 'media', name: 'Media & PR', domain: 'media' as const, members: 7 },
  { slug: 'management', name: 'Management', domain: 'management' as const, members: 6 },
];

export const OCCASIONS = [
  { id: 'o-1', person: PEOPLE.karan, kind: 'Birthday' },
  { id: 'o-2', person: PEOPLE.nithya, kind: 'Birthday' },
];

export const ANNOUNCEMENTS = [
  {
    id: 'a-1',
    title: 'Techfest brief is locked',
    body: 'Domain leads: pull your deliverables from the shared drive before Friday. Anything not in by then ships in the second wave.',
    by: PEOPLE.riya,
    at: ago(20),
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: 't-0142',
    number: '#0142',
    title: 'Birthday poster - Ananya Rao (04 Sep)',
    description:
      'Square and story crops, club palette, name spelled exactly as on the roster. Post goes out at 09:00 on the day.',
    domain: 'design',
    boardSlug: 'design',
    boardName: 'Design',
    state: 'progress',
    priority: 'medium',
    assignees: [PEOPLE.ananya],
    due: iso(0),
    labels: ['poster', 'social'],
    source: { kind: 'occasion', label: 'Birthday - Ananya Rao', ref: 'o-9' },
    checklist: [
      { id: 'c1', text: 'Square crop', done: true },
      { id: 'c2', text: 'Story crop', done: true },
      { id: 'c3', text: 'Name and date proofread', done: false },
    ],
    deliverables: [
      { id: 'd1', url: 'https://figma.com/file/abc', label: 'Figma - birthday set', provider: 'figma', shared: true },
    ],
    comments: [
      { id: 'm1', author: PEOPLE.riya, body: 'Use last month’s template, it read well on phones.', at: ago(26) },
    ],
    activity: [
      { id: 'v1', text: 'moved to In progress', at: ago(28), actor: PEOPLE.ananya },
      { id: 'v2', text: 'generated from the birthday occasion', at: ago(72) },
    ],
    createdAt: iso(-3),
  },
  {
    id: 't-0117',
    number: '#0117',
    title: 'Confirm auditorium booking and get written approval',
    description:
      'Campus admin wants the stamped requisition before they release the main stage. Chase the office in person if email stalls again.',
    domain: 'events',
    boardSlug: 'events',
    boardName: 'Events',
    committee: 'Techfest',
    state: 'blocked',
    priority: 'urgent',
    assignees: [PEOPLE.karan, PEOPLE.arjun],
    due: iso(-3),
    labels: ['venue'],
    blockedReason: 'Admin office is holding it until the requisition is stamped.',
    checklist: [
      { id: 'c1', text: 'Submit requisition form', done: true },
      { id: 'c2', text: 'Get endorsement', done: true },
      { id: 'c3', text: 'Receive stamped confirmation', done: false },
    ],
    deliverables: [],
    comments: [
      { id: 'm1', author: PEOPLE.karan, body: 'Went in person Tuesday. Told to come back Thursday.', at: ago(30) },
    ],
    activity: [{ id: 'v1', text: 'flagged as Blocked', at: ago(30), actor: PEOPLE.karan }],
    createdAt: iso(-14),
  },
  {
    id: 't-0138',
    number: '#0138',
    title: 'Ship the registration form validation',
    description: 'Client and server both. Reject duplicate roll numbers with a message that names the clash.',
    domain: 'technical',
    boardSlug: 'technical',
    boardName: 'Technical',
    committee: 'Techfest',
    state: 'review',
    priority: 'high',
    assignees: [PEOPLE.nithya],
    due: iso(-1),
    labels: ['forms'],
    checklist: [],
    deliverables: [
      { id: 'd1', url: 'https://github.com/inovx/ops/pull/48', label: 'PR #48', provider: 'github', shared: true },
    ],
    comments: [],
    activity: [{ id: 'v1', text: 'submitted for review', at: ago(18), actor: PEOPLE.nithya }],
    createdAt: iso(-9),
  },
  {
    id: 't-0151',
    number: '#0151',
    title: 'Techfest teaser reel - first cut',
    description: 'Sixty seconds, vertical, no licensed music. Pull last year’s footage from the archive drive.',
    domain: 'media',
    boardSlug: 'media',
    boardName: 'Media & PR',
    committee: 'Techfest',
    state: 'todo',
    priority: 'high',
    assignees: [PEOPLE.dev],
    due: iso(2),
    labels: ['video'],
    checklist: [
      { id: 'c1', text: 'Pull archive footage', done: false },
      { id: 'c2', text: 'Rough cut', done: false },
    ],
    deliverables: [
      { id: 'd1', url: 'https://drive.google.com/file/xyz', label: 'Archive footage', provider: 'drive', shared: false },
    ],
    comments: [],
    activity: [],
    createdAt: iso(-2),
  },
  {
    id: 't-0149',
    number: '#0149',
    title: 'Sponsor deck - refresh the numbers',
    description: 'Last year’s footfall and reach, plus the two new partners. Keep it to eight slides.',
    domain: 'management',
    boardSlug: 'management',
    boardName: 'Management',
    state: 'progress',
    priority: 'high',
    assignees: [PEOPLE.sana],
    due: iso(0),
    labels: ['sponsors'],
    checklist: [{ id: 'c1', text: 'Pull last year’s numbers', done: true }],
    deliverables: [],
    comments: [],
    activity: [],
    createdAt: iso(-5),
  },
  {
    id: 't-0153',
    number: '#0153',
    title: 'Stage backdrop - print-ready artwork',
    description: 'Twelve by eight feet at 150dpi, CMYK, 50mm bleed. Printer needs it Monday to hit the date.',
    domain: 'design',
    boardSlug: 'design',
    boardName: 'Design',
    committee: 'Techfest',
    state: 'todo',
    priority: 'urgent',
    assignees: [PEOPLE.ananya],
    due: iso(0),
    labels: ['print'],
    checklist: [],
    deliverables: [],
    comments: [],
    activity: [],
    createdAt: iso(-1),
  },
  {
    id: 't-0140',
    number: '#0140',
    title: 'Instagram carousel - speaker announcement',
    description: 'Five slides, one speaker each, headshot plus a one-line credential.',
    domain: 'design',
    boardSlug: 'design',
    boardName: 'Design',
    state: 'review',
    priority: 'medium',
    assignees: [PEOPLE.ananya],
    due: iso(-1),
    labels: ['social'],
    checklist: [],
    deliverables: [
      { id: 'd1', url: 'https://figma.com/file/def', label: 'Figma - carousel', provider: 'figma', shared: true },
    ],
    comments: [],
    activity: [{ id: 'v1', text: 'submitted for review', at: ago(40), actor: PEOPLE.ananya }],
    createdAt: iso(-6),
  },
  {
    id: 't-0144',
    number: '#0144',
    title: 'Volunteer roster for day one',
    description: 'Two shifts, sixteen slots. Nobody on more than one shift.',
    domain: 'events',
    boardSlug: 'events',
    boardName: 'Events',
    state: 'todo',
    priority: 'medium',
    assignees: [PEOPLE.arjun],
    due: iso(4),
    labels: [],
    checklist: [],
    deliverables: [],
    comments: [],
    activity: [],
    createdAt: iso(-4),
  },
  {
    id: 't-0131',
    number: '#0131',
    title: 'Club website - swap the hero to Techfest',
    description: 'Hero image, date strip, and a register button pointing at the new form.',
    domain: 'technical',
    boardSlug: 'technical',
    boardName: 'Technical',
    state: 'done',
    priority: 'medium',
    assignees: [PEOPLE.nithya],
    due: iso(-4),
    labels: ['web'],
    checklist: [],
    deliverables: [],
    comments: [],
    activity: [{ id: 'v1', text: 'approved', at: ago(50), actor: PEOPLE.riya }],
    createdAt: iso(-12),
  },
  {
    id: 't-0128',
    number: '#0128',
    title: 'Print the volunteer badges',
    description: 'Sixty badges, lanyard punch, names as on the roster.',
    domain: 'design',
    boardSlug: 'design',
    boardName: 'Design',
    state: 'done',
    priority: 'low',
    assignees: [PEOPLE.ananya],
    due: iso(-6),
    labels: ['print'],
    checklist: [],
    deliverables: [],
    comments: [],
    activity: [],
    createdAt: iso(-15),
  },
  {
    id: 't-0155',
    number: '#0155',
    title: 'Weekly recap post',
    description: 'What shipped this week, in three lines and one image.',
    domain: 'media',
    boardSlug: 'media',
    boardName: 'Media & PR',
    state: 'todo',
    priority: 'low',
    assignees: [PEOPLE.dev],
    due: iso(5),
    labels: ['social'],
    source: { kind: 'recurring', label: 'Weekly recap - every Friday', ref: 'r-3' },
    checklist: [],
    deliverables: [],
    comments: [],
    activity: [],
    createdAt: iso(0),
  },
  {
    id: 't-0156',
    number: '#0156',
    title: 'Photograph the setup crew',
    description: 'Generated from the backdrop task so the print run gets documented.',
    domain: 'media',
    boardSlug: 'media',
    boardName: 'Media & PR',
    state: 'todo',
    priority: 'low',
    assignees: [PEOPLE.dev],
    due: iso(6),
    labels: [],
    source: { kind: 'task', label: 'Stage backdrop - print-ready artwork', ref: '#0153' },
    checklist: [],
    deliverables: [],
    comments: [],
    activity: [],
    createdAt: iso(0),
  },
  {
    id: 't-0157',
    number: '#0157',
    title: 'Book the shuttle for the guest speakers',
    description: 'Two pickups, both from the north gate. Confirm with the travel desk by Wednesday.',
    domain: 'events',
    boardSlug: 'events',
    boardName: 'Events',
    state: 'progress',
    priority: 'medium',
    assignees: [PEOPLE.arjun, PEOPLE.karan, PEOPLE.sana, PEOPLE.riya],
    due: iso(3),
    labels: ['travel'],
    checklist: [],
    deliverables: [],
    comments: [],
    activity: [],
    createdAt: iso(-2),
  },
  {
    id: 't-0158',
    number: '#0158',
    title: 'Archive last year’s assets',
    description: 'Superseded by the new brand kit - kept for reference only.',
    domain: 'design',
    boardSlug: 'design',
    boardName: 'Design',
    state: 'cancelled',
    priority: 'low',
    assignees: [],
    due: null,
    labels: [],
    checklist: [],
    deliverables: [],
    comments: [],
    activity: [],
    createdAt: iso(-20),
  },
];

/**
 * TEMP: maps a signed-in account to the person the task data knows about.
 * The real session will carry the person id and this goes away.
 */
export const PERSON_BY_EMAIL: Record<string, Person> = {
  'riya@inovx.club': PEOPLE.riya,
  'arjun@inovx.club': PEOPLE.arjun,
  'member@inovx.club': PEOPLE.ananya,
  'faculty@inovx.club': PEOPLE.riya,
};
