-- ==============================================================================
-- INOVX OPS — THE BIRTHDAYS, AT LAST
-- Migration: 20260920000000_birthdays.sql
-- ==============================================================================
--
-- GENERATED by scripts/import-birthdays.mjs from
--   https://adizzsk23.github.io/inovx-member-cards/data/members.json
-- (that file's own `generated` stamp: 2026-08-21)
-- Re-run the script rather than editing this by hand.
--
-- The gap this closes
-- -------------------
-- `member_directory.birthday` has been NULL for everyone since the club was
-- seeded, and the seed said so out loud: "Birthdays are left NULL because
-- nobody has collected them." Three finished surfaces have been reading that
-- NULL ever since and showing nothing — `upcomingBirthdays()` behind §9.10's
-- BIRTHDAYS tab, the Calendar's occasions layer, and the occasion generator at
-- the end of seed_club_only.sql, which selects `WHERE birthday IS NOT NULL`
-- and has therefore always selected nothing.
--
-- Nothing here invents a date. 30 of the roster have one on the cards
-- site; the rest keep their NULL and generate no occasion, and the People screen
-- will keep saying so rather than filling the gap with a guess.

-- ------------------------------------------------------------------------------
-- 1. The dates
-- ------------------------------------------------------------------------------
-- Matched on email. The two rosters disagree about several spellings of the
-- same person's name and agree about every address.
WITH incoming (email, dob) AS (
  VALUES
  ('akash.d.2025.csbs@rajalakshmi.edu.in', DATE '2008-02-14'),  -- Akash D
  ('assvine.s.2025.csbs@rajalakshmi.edu.in', DATE '2007-10-27'),  -- Ashwini S
  ('athithya.r.2024.csbs@rajalakshmi.edu.in', DATE '2006-08-22'),  -- Athithya R
  ('bhuvaneswaran.s.2025.cse@rajalakshmi.edu.in', DATE '2007-12-31'),  -- Bhuvaneswaran S
  ('chandanashankari.2025.it@rajalakshmi.edu.in', DATE '2007-11-27'),  -- Chandana Shankari
  ('devanand.c.2025.eee@rajalakshmi.edu.in', DATE '2007-10-14'),  -- Devanand C
  ('gayathri.s1.2025.cse@rajalakshmi.edu.in', DATE '2007-08-27'),  -- Gayathri S
  ('harini.m1.2025.cse@rajalakshmi.edu.in', DATE '2008-02-18'),  -- Harini M
  ('harini.s.2025.cse@rajalakshmi.edu.in', DATE '2008-03-16'),  -- Harini S
  ('jaiharish.d.2024.cse@rajalakshmi.edu.in', DATE '2006-10-30'),  -- Jaiharish D
  ('jaswanthgunasekaran.2025.cse@rajalakshmi.edu.in', DATE '2008-01-10'),  -- Jaswanth G
  ('katelynsanjanakhanna.2025.csd@rajalakshmi.edu.in', DATE '2007-09-09'),  -- Katelyn Sanjana Khanna
  ('laxmigayathiri.s.2025.aids@rajalakshmi.edu.in', DATE '2008-01-16'),  -- Laxmi Gayathiri S
  ('lingeesh.l.2025.ft@rajalakshmi.edu.in', DATE '2007-10-27'),  -- Lingeesh L
  ('mayanksharma.2025.aiml@rajalakshmi.edu.in', DATE '2008-05-13'),  -- Mayank Sharm
  ('mohamedirfan.s.2025.csecs@rajalakshmi.edu.in', DATE '2008-01-26'),  -- Mohamed Irfan S
  ('pavanprasad.p.2025.it@rajalakshmi.edu.in', DATE '2007-07-19'),  -- PavanPrasad P
  ('pooja.r.2025.csbs@rajalakshmi.edu.in', DATE '2008-07-18'),  -- Pooja R
  ('praveensundar.r.2025.eee@rajalakshmi.edu.in', DATE '2007-04-01'),  -- Praveen Sundar R
  ('ragamithra.kb.2025.csbs@rajalakshmi.edu.in', DATE '2007-12-05'),  -- Ragamithra K B
  ('sandhiya.p.2025.csbs@rajalakshmi.edu.in', DATE '2008-05-31'),  -- Sandhiya P
  ('sanjanabanerjee.2025.cse@rajalakshmi.edu.in', DATE '2007-10-09'),  -- Sanjana Banerjee
  ('sanjeevkumar.k.2025.mct@rajalakshmi.edu.in', DATE '2007-05-11'),  -- K Sanjeev Kumar
  ('sreevishal.ks.2025.it@rajalakshmi.edu.in', DATE '2007-06-24'),  -- K.S. Sree Vishal
  ('subeesh.s.2024.bt@rajalakshmi.edu.in', DATE '2006-05-21'),  -- Subeesh S
  ('tharika.r.2024.csbs@rajalakshmi.edu.in', DATE '2007-01-24'),  -- Tharika R
  ('varun.ms.2025.cse@rajalakshmi.edu.in', DATE '2007-11-23'),  -- M S Varun
  ('vijayalakshmiradhakrishnan.2025.csbs@rajalakshmi.edu.in', DATE '2007-11-30'),  -- Vijayalakshmi Radhakrishnan
  ('visal.g.2025.mech@rajalakshmi.edu.in', DATE '2008-01-19'),  -- Visal G
  ('visshwajit.pr.2025.mech@rajalakshmi.edu.in', DATE '2007-11-20')   -- P.R. Visshwajit
)
UPDATE member_directory md
SET birthday = incoming.dob
FROM incoming
WHERE LOWER(md.email) = incoming.email
  AND md.tenure_id = '11111111-1111-1111-1111-111111111111'
  AND md.birthday IS DISTINCT FROM incoming.dob;

-- ------------------------------------------------------------------------------
-- 2. Tie a generated task back to the occasion that asked for it
-- ------------------------------------------------------------------------------
-- Until now the Calendar worked out which tasks an occasion produced by
-- searching task titles for the person's first name (src/lib/club.ts). That is
-- a guess: it misses a poster titled "Sandhiya bday banner" and it claims one
-- titled "Harini to review the Harini poster" twice. The birthday reminders in
-- the next migration have to answer "has this actually been made" exactly, so
-- the link becomes a column.
ALTER TABLE tasks
  ADD COLUMN IF NOT EXISTS occasion_id UUID REFERENCES occasions(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_tasks_occasion ON tasks(occasion_id) WHERE occasion_id IS NOT NULL;

-- ------------------------------------------------------------------------------
-- 3. Raise the occasions the dates now make possible
-- ------------------------------------------------------------------------------
-- The same SELECT the seed has always carried, run now that it has rows to find.
-- Design owns the output because the club's posters are Design's work; lead_days
-- stays at the seed's 5 so the board shows the work coming before the reminders
-- start. `uq_occasions_tenure_name` makes the re-run harmless.
INSERT INTO occasions (
  tenure_id, name, occasion_type, occasion_date,
  output_domain_id, lead_days, assignment_strategy, directory_member_id
)
SELECT
  md.tenure_id,
  md.name || ' — birthday',
  'birthday',
  TO_CHAR(md.birthday, 'MM-DD'),
  '22222222-2222-2222-2222-000000000005',
  5,
  'domain-lead',
  md.id
FROM member_directory md
WHERE md.tenure_id = '11111111-1111-1111-1111-111111111111'
  AND md.birthday IS NOT NULL
ON CONFLICT (tenure_id, name) DO NOTHING;

-- A birthday corrected above should correct the occasion with it, rather than
-- leaving the poster scheduled against last week's date.
UPDATE occasions o
SET occasion_date = TO_CHAR(md.birthday, 'MM-DD')
FROM member_directory md
WHERE o.directory_member_id = md.id
  AND o.occasion_type = 'birthday'
  AND md.birthday IS NOT NULL
  AND o.occasion_date IS DISTINCT FROM TO_CHAR(md.birthday, 'MM-DD');
